# docker-compose.yml

version: '3.5'

services:
  app:
    container_name: bluebus-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: npm run deploy
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - '/usr/src/app/build'
